### ISSUE TITLE
are there any sample code to download and run/test?

### ISSUE THREAD

**Issue by Byzero512** [airbus-seclab/qemu_blog#1]
are there open source code of the entire repo for learning and testing?

**Comment by sduverger** [comment]
Hi,

Unfortunately, the complete CPIOM board is not open-source.
However, I would suggest you to start with a simple board available in the official QEMU source tree, and try to hack it.
The MIPS R4K (https://github.com/qemu/qemu/blob/v4.2.0/hw/mips/mips_r4k.c#L167) is a pretty simple one for instance.

**Comment by Byzero512** [comment]
oh, what a pity.
Thanks for advice.
