### ISSUE TITLE
get memory content

### ISSUE THREAD

**Issue by quantrpeter** [airbus-seclab/qemu_blog#2]
Hi All
   Which function can get the content of physical memory?
thanks
Peter

**Comment by sduverger** [comment]
Hello,

TL;DR: cpu_physical_memory_rw()

Look at https://airbus-seclab.github.io/qemu_blog/regions.html
Then https://github.com/qemu/qemu/blob/v4.2.0/docs/devel/loads-stores.rst
And ideally at https://github.com/qemu/qemu/blob/v4.2.0/exec.c#L3275

The QEMU monitor has a 'xp' command, you can have a look at its implementation too :)

**Comment by quantrpeter** [comment]
Thanks @sduverger
