### ISSUE TITLE
Machine or Devices for hello world for arm

### ISSUE THREAD

**Issue by AbhijitInamdar5** [airbus-seclab/qemu_blog#3]
Hi,

I tried to followed your blog and created a c-file in hw/arm for my custom with the following MachineClass and MachineState and "init" for a minimal hello world program. So will it be a machine or a device? and the c-file is being read(did some debugging) but its not able to print hello world! I'm not getting where exactly is the problem.  As the same c-file is running in qemu-2.10 but not in qemu-4.2.0(made the required changes). 

Thank you in advance.

**Comment by sduverger** [comment]
Hello,

I don't exactly understand what you are trying to do. But if you want to do an "hello world", it's up to you. You can either create a new board (and so define a MachineClass) or a new device that you will eventually attach to an existing board to test it.

However, to be able to test a new board or device, you will need some firmware code (drivers) that will interact with this virtual hardware.

A lot of API changed between 2.10 and 4.2. That's no surprise it's not working as-is. Use qemu_log() to print debug info and most importantly the qemu monitor :)

**Comment by AbhijitInamdar5** [comment]
I just want to create a machine(cortex-m3 based) to do a basic "hello world" print on the terminal. I have the required startup and linker scripts from https://github.com/ARM-software/CMSIS_5/tree/develop/Device/ARM/ARMCM3/Source/GCC. 

I have checked with the c-file of my machine its being read correctly. 

I tried using -D /log.txt but the file is empty. Is it the correct way to use ?

**Comment by AbhijitInamdar5** [comment]
Hi, I have made the linker and startup accordingly and I tried to use qemu_log() : -d in_asm,cpu -D /qemu.log is this the right way for debug info? and what did you mean by "most importantly the qemu monitor" ? 

The gcc command is : ../../gcc-arm/gcc-arm-none-eabi-6-2017-q2-update/bin/arm-none-eabi-gcc hello_world.c startup_ARMCM31.S -mthumb -mcpu=cortex-m3 -D__STARTUP_CLEAR_BSS -D__START=main -Os -flto -ffunction-sections -fdata-sections --specs=nano.specs --specs=rdimon.specs -Wl,--gc-sections -Wl,-Map=main.map -T machine.ld -o main.axf

The qemu command line I'm using is : ../../qemu-4.2.0/build/arm-softmmu/qemu-system-arm -M machine -cpu cortex-m3 -kernel main.axf -monitor none -serial stdio -semihosting -nographic
