### ISSUE TITLE
Image not rendering on your website

### ISSUE THREAD

**Issue by freakynit** [airbus-seclab/qemu_blog#5]
Hi.. first, thanks for the brilliant write-up.

Now the issue: On this link: https://airbus-seclab.github.io/qemu_blog/machine.html, the architecture image beneath `The CPIOM machine` heading isn't rendering on website.

See screenshot:
<img width="499" alt="Screenshot 2022-08-22 at 9 54 59 PM" src="https://user-images.githubusercontent.com/745352/185970988-30aece02-66ec-4788-8e0c-ab2b23548eb8.png">

Not sure if this image only is affected, or all.

Thanks..

**Comment by sduverger** [comment]
Hi,

Thank you. The image is correctly rendered when reading the markdown file
directly on github.com rather than github.io pages. As a workaround …

We should investigate why however :)

Le lun. 22 août 2022 à 18:25, Nitin Bansal ***@***.***> a
écrit :
