### ISSUE TITLE
How to get the process that the basic block being translated in system mode belongs to?

### ISSUE THREAD

**Issue by 14isnot40** [airbus-seclab/qemu_blog#7]
Thanks to this repository for giving me a deeper understanding of QEMU's internals.
One of my doubts now is whether QEMU can obtain the process information to which the basic block to be translated currently belongs, such as process pid or process name. What QEMU's internal APIs should be used to get information about processes if possible?

**Comment by sduverger** [comment]
QEMU is agnostic to the OS kernel it is running and does not provide any introspection API for a particular OS kernel.
If you intercept or fix qemu code at basic block translation level and are able to inspect the CPU state, then you will be able to access required information (kernel stack pointer, page directory, ...)  to recover you process information, but it will largely depend on your target OS kernel.
